import { useState, useMemo } from 'react'
import {
  Calculator, DollarSign, TrendingUp, Home, Wrench,
  Download, ChevronDown, ChevronUp, Lightbulb,
  Percent, RotateCcw, ArrowRightLeft,
  CheckCircle2, AlertTriangle, Key, RefreshCw,
} from 'lucide-react'

/* ── helpers ──────────────────────────────────────── */
function fmt(n: number) {
  if (!n && n !== 0) return '$0'
  return '$' + Math.round(n).toLocaleString('en-US')
}
function pct(n: number) {
  if (!isFinite(n)) return '0.0%'
  return (n * 100).toFixed(1) + '%'
}
function monthlyPayment(principal: number, annualRate: number, years: number) {
  if (principal <= 0 || annualRate <= 0 || years <= 0) return 0
  const r = annualRate / 100 / 12
  const n = years * 12
  return principal * (r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1)
}

type Strategy = 'flip' | 'rent' | 'hold' | 'brrrr'

const STRATEGIES: { id: Strategy; label: string; desc: string; icon: typeof Home }[] = [
  { id: 'flip', label: 'Fix & Flip', desc: 'Buy, rehab, sell for profit', icon: ArrowRightLeft },
  { id: 'rent', label: 'Buy & Rent', desc: 'Purchase and hold for rental income', icon: Key },
  { id: 'hold', label: 'Buy & Hold', desc: 'Long-term appreciation play', icon: TrendingUp },
  { id: 'brrrr', label: 'BRRRR', desc: 'Buy, Rehab, Rent, Refinance, Repeat', icon: RefreshCw },
]

/* ── Shared input component ───────────────────────── */
function Field({ label, icon: Icon, required, children, color }: {
  label: string; icon?: typeof Home; required?: boolean; children: React.ReactNode; color?: string
}) {
  return (
    <div>
      <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: color || '#888', marginBottom: 6, fontWeight: required ? 600 : 400 }}>
        {Icon && <Icon size={12} />} {label} {required && '*'}
      </label>
      {children}
    </div>
  )
}

/* ── Download helpers ─────────────────────────────── */
function downloadReport(title: string, lines: string[]) {
  const text = `${title}\nGenerated: ${new Date().toLocaleDateString()}\n\n${lines.join('\n')}\n\n---\nGenerated by Flip the Contract — Investment Strategy Calculator\nFor educational purposes only. Always verify with your own due diligence.\n© 2026 Flip the Contract. All rights reserved.`
  const blob = new Blob([text], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Investment_Analysis_${title.replace(/\s+/g, '_')}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/* ── Result card component ────────────────────────── */
function MetricCard({ label, value, color, sub }: { label: string; value: string; color?: string; sub?: string }) {
  return (
    <div style={{ background: '#263040', borderRadius: 8, padding: 16, textAlign: 'center', minWidth: 0 }}>
      <div style={{ fontSize: 11, color: '#888', marginBottom: 4, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{label}</div>
      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, color: color || '#f5f0eb', lineHeight: 1.2 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: '#666', marginTop: 4 }}>{sub}</div>}
    </div>
  )
}

function CostLine({ label, amount, dotColor }: { label: string; amount: number; dotColor?: string }) {
  return (
    <div style={{
      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      padding: '10px 14px', background: '#2e3a4d', borderRadius: 6,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0, flex: 1 }}>
        <div style={{ width: 6, height: 6, borderRadius: '50%', background: dotColor || '#5ba3d9', flexShrink: 0 }} />
        <span style={{ fontSize: 13, color: '#ccc', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{label}</span>
      </div>
      <span style={{ fontSize: 14, color: '#f5f0eb', fontWeight: 600, fontFamily: "'DM Sans', sans-serif", flexShrink: 0, marginLeft: 8 }}>
        {fmt(amount)}
      </span>
    </div>
  )
}

/* ══════════════════════════════════════════════════ */
/* ── MAIN COMPONENT ─────────────────────────────── */
/* ══════════════════════════════════════════════════ */
export default function InvestmentStrategyCalc() {
  const [strategy, setStrategy] = useState<Strategy>('flip')
  const [calculated, setCalculated] = useState(false)
  const [showAdvanced, setShowAdvanced] = useState(false)

  /* ── Shared inputs ── */
  const [address, setAddress] = useState('')
  const [purchasePrice, setPurchasePrice] = useState('')
  const [arv, setArv] = useState('')
  const [rehabCost, setRehabCost] = useState('')
  const [closingCostPct, setClosingCostPct] = useState('3')

  /* ── Flip-specific ── */
  const [holdingMonths, setHoldingMonths] = useState('6')
  const [realtorPct, setRealtorPct] = useState('5')
  const [sellingClosingPct] = useState('2')
  const [financingCostPct, setFinancingCostPct] = useState('12')

  /* ── Rent / Hold / BRRRR ── */
  const [monthlyRent, setMonthlyRent] = useState('')
  const [downPaymentPct, setDownPaymentPct] = useState('20')
  const [interestRate, setInterestRate] = useState('7')
  const [loanTermYears, setLoanTermYears] = useState('30')
  const [propertyTaxAnnual, setPropertyTaxAnnual] = useState('')
  const [insuranceAnnual, setInsuranceAnnual] = useState('')
  const [maintenancePct, setMaintenancePct] = useState('5')
  const [vacancyPct, setVacancyPct] = useState('8')
  const [mgmtPct, setMgmtPct] = useState('10')
  const [appreciationPct, setAppreciationPct] = useState('3')

  /* ── BRRRR-specific ── */
  const [refinanceLtv, setRefinanceLtv] = useState('75')
  const [refinanceRate, setRefinanceRate] = useState('7')
  const [refinanceTermYears, setRefinanceTermYears] = useState('30')
  const [seasoning, setSeasoning] = useState('6')

  /* ── Parse ── */
  const pp = parseFloat(purchasePrice) || 0
  const arvN = parseFloat(arv) || 0
  const rehab = parseFloat(rehabCost) || 0
  const closingPct = parseFloat(closingCostPct) || 3
  const holdMo = parseFloat(holdingMonths) || 6
  const realtorP = parseFloat(realtorPct) || 5
  const sellClosePct = parseFloat(sellingClosingPct) || 2
  const finCostPct = parseFloat(financingCostPct) || 12
  const rent = parseFloat(monthlyRent) || 0
  const dpPct = parseFloat(downPaymentPct) || 20
  const intRate = parseFloat(interestRate) || 7
  const loanYears = parseFloat(loanTermYears) || 30
  const taxAnnual = parseFloat(propertyTaxAnnual) || 0
  const insAnnual = parseFloat(insuranceAnnual) || 0
  const maintPct = parseFloat(maintenancePct) || 5
  const vacPct = parseFloat(vacancyPct) || 8
  const mgmtP = parseFloat(mgmtPct) || 10
  const apprPct = parseFloat(appreciationPct) || 3
  const refiLtv = parseFloat(refinanceLtv) || 75
  const refiRate = parseFloat(refinanceRate) || 7
  const refiYears = parseFloat(refinanceTermYears) || 30
  const seasonMo = parseFloat(seasoning) || 6

  /* ══════════════════════════════════════════════ */
  /* ── CALCULATIONS ─────────────────────────────── */
  /* ══════════════════════════════════════════════ */
  const results = useMemo(() => {
    /* ─── FIX & FLIP ──────────────────────────── */
    if (strategy === 'flip') {
      const buyClosing = pp * (closingPct / 100)
      const totalAcquisition = pp + buyClosing
      const holdingCosts = pp * 0.01 * holdMo // taxes, insurance, utilities ~1%/mo
      const financingCosts = pp * (finCostPct / 100 / 12) * holdMo
      const sellingCosts = arvN * (realtorP / 100) + arvN * (sellClosePct / 100)
      const totalInvestment = totalAcquisition + rehab + holdingCosts + financingCosts + sellingCosts
      const netProfit = arvN - totalInvestment
      const roi = totalInvestment > 0 ? netProfit / (pp + buyClosing + rehab) : 0
      const annualizedRoi = holdMo > 0 ? (Math.pow(1 + roi, 12 / holdMo) - 1) : 0
      const profitPerMonth = holdMo > 0 ? netProfit / holdMo : 0

      let verdict = ''
      let verdictColor = ''
      if (roi >= 0.20) { verdict = 'Strong Flip — Excellent margins'; verdictColor = '#5cb885' }
      else if (roi >= 0.10) { verdict = 'Decent Flip — Good margins'; verdictColor = '#eab308' }
      else if (roi > 0) { verdict = 'Thin Flip — Tight margins'; verdictColor = '#e8a44a' }
      else { verdict = 'No Deal — Numbers don\'t work'; verdictColor = '#ef4444' }

      return {
        strategy: 'flip' as const,
        totalAcquisition, rehab, holdingCosts, financingCosts, sellingCosts,
        totalInvestment, netProfit, roi, annualizedRoi, profitPerMonth,
        verdict, verdictColor, buyClosing,
        costs: [
          { label: 'Purchase Price', amount: pp, color: '#5ba3d9' },
          { label: 'Buying Closing Costs', amount: buyClosing, color: '#5ba3d9' },
          { label: 'Rehab / Repairs', amount: rehab, color: '#e8a44a' },
          { label: `Holding Costs (${holdMo} mo)`, amount: holdingCosts, color: '#a855f7' },
          { label: `Financing Costs (${finCostPct}% APR)`, amount: financingCosts, color: '#a855f7' },
          { label: `Realtor Commission (${realtorP}%)`, amount: arvN * (realtorP / 100), color: '#ff7e5f' },
          { label: `Selling Closing Costs (${sellClosePct}%)`, amount: arvN * (sellClosePct / 100), color: '#ff7e5f' },
        ],
      }
    }

    /* ─── BUY & RENT ─────────────────────────── */
    if (strategy === 'rent') {
      const downPayment = pp * (dpPct / 100)
      const loanAmount = pp - downPayment
      const buyClosing = pp * (closingPct / 100)
      const cashInvested = downPayment + buyClosing + rehab
      const monthlyMortgage = monthlyPayment(loanAmount, intRate, loanYears)
      const monthlyTax = taxAnnual / 12
      const monthlyIns = insAnnual / 12
      const monthlyMaint = rent * (maintPct / 100)
      const monthlyVacancy = rent * (vacPct / 100)
      const monthlyMgmt = rent * (mgmtP / 100)
      const totalMonthlyExpenses = monthlyMortgage + monthlyTax + monthlyIns + monthlyMaint + monthlyVacancy + monthlyMgmt
      const monthlyCashFlow = rent - totalMonthlyExpenses
      const annualCashFlow = monthlyCashFlow * 12
      const cashOnCashReturn = cashInvested > 0 ? annualCashFlow / cashInvested : 0

      // NOI = Net Operating Income (before debt service)
      const annualNOI = (rent * 12) - (monthlyTax * 12) - (monthlyIns * 12) - (monthlyMaint * 12) - (monthlyVacancy * 12) - (monthlyMgmt * 12)
      const capRate = pp > 0 ? annualNOI / pp : 0
      const grm = rent > 0 ? pp / (rent * 12) : 0
      const dscr = monthlyMortgage > 0 ? (annualNOI / 12) / monthlyMortgage : 0

      // 5-year projection
      const fiveYearEquity = pp * Math.pow(1 + apprPct / 100, 5) - loanAmount * 0.92 // rough principal paydown
      const fiveYearCashFlow = annualCashFlow * 5
      const fiveYearTotalReturn = fiveYearEquity - pp + fiveYearCashFlow

      let verdict = ''
      let verdictColor = ''
      if (monthlyCashFlow >= 300 && cashOnCashReturn >= 0.08) { verdict = 'Strong Rental — Great cash flow'; verdictColor = '#5cb885' }
      else if (monthlyCashFlow >= 100 && cashOnCashReturn >= 0.05) { verdict = 'Decent Rental — Acceptable returns'; verdictColor = '#eab308' }
      else if (monthlyCashFlow > 0) { verdict = 'Thin Rental — Low cash flow'; verdictColor = '#e8a44a' }
      else { verdict = 'Negative Cash Flow — Numbers don\'t work'; verdictColor = '#ef4444' }

      return {
        strategy: 'rent' as const,
        cashInvested, downPayment, loanAmount, buyClosing,
        monthlyMortgage, monthlyTax, monthlyIns, monthlyMaint, monthlyVacancy, monthlyMgmt,
        totalMonthlyExpenses, monthlyCashFlow, annualCashFlow,
        cashOnCashReturn, annualNOI, capRate, grm, dscr,
        fiveYearEquity, fiveYearCashFlow, fiveYearTotalReturn,
        verdict, verdictColor,
        expenses: [
          { label: 'Mortgage (P&I)', amount: monthlyMortgage, color: '#5ba3d9' },
          { label: 'Property Tax', amount: monthlyTax, color: '#a855f7' },
          { label: 'Insurance', amount: monthlyIns, color: '#a855f7' },
          { label: `Maintenance (${maintPct}%)`, amount: monthlyMaint, color: '#e8a44a' },
          { label: `Vacancy (${vacPct}%)`, amount: monthlyVacancy, color: '#e8a44a' },
          { label: `Management (${mgmtP}%)`, amount: monthlyMgmt, color: '#ff7e5f' },
        ],
      }
    }

    /* ─── BUY & HOLD ─────────────────────────── */
    if (strategy === 'hold') {
      const downPayment = pp * (dpPct / 100)
      const loanAmount = pp - downPayment
      const buyClosing = pp * (closingPct / 100)
      const cashInvested = downPayment + buyClosing + rehab
      const monthlyMortgage = monthlyPayment(loanAmount, intRate, loanYears)
      const monthlyTax = taxAnnual / 12
      const monthlyIns = insAnnual / 12
      const monthlyMaint = rent * (maintPct / 100)
      const monthlyVacancy = rent * (vacPct / 100)
      const monthlyMgmt = rent * (mgmtP / 100)
      const totalMonthlyExpenses = monthlyMortgage + monthlyTax + monthlyIns + monthlyMaint + monthlyVacancy + monthlyMgmt
      const monthlyCashFlow = rent - totalMonthlyExpenses
      const annualCashFlow = monthlyCashFlow * 12
      const cashOnCashReturn = cashInvested > 0 ? annualCashFlow / cashInvested : 0
      const annualNOI = (rent * 12) - (monthlyTax * 12) - (monthlyIns * 12) - (monthlyMaint * 12) - (monthlyVacancy * 12) - (monthlyMgmt * 12)
      const capRate = pp > 0 ? annualNOI / pp : 0

      // Multi-year wealth building projection
      const years = [1, 3, 5, 10, 15, 20, 30]
      const projections = years.map(y => {
        const futureValue = pp * Math.pow(1 + apprPct / 100, y)
        const appreciation = futureValue - pp
        // Approximate remaining loan balance using amortization formula
        const r = intRate / 100 / 12
        const totalPayments = loanYears * 12
        const paymentsMade = y * 12
        const remainingBalance = paymentsMade >= totalPayments ? 0 :
          loanAmount * (Math.pow(1 + r, totalPayments) - Math.pow(1 + r, paymentsMade)) / (Math.pow(1 + r, totalPayments) - 1)
        const equity = futureValue - remainingBalance
        const totalCashFlow = annualCashFlow * y
        const totalReturn = equity - cashInvested + totalCashFlow
        const annualizedReturn = cashInvested > 0 ? (Math.pow(1 + totalReturn / cashInvested, 1 / y) - 1) : 0
        return { year: y, futureValue, appreciation, equity, totalCashFlow, totalReturn, annualizedReturn, remainingBalance }
      })

      let verdict = ''
      let verdictColor = ''
      const tenYearReturn = projections.find(p => p.year === 10)
      if (tenYearReturn && cashInvested > 0 && tenYearReturn.totalReturn / cashInvested >= 2) {
        verdict = 'Strong Hold — Excellent long-term potential'; verdictColor = '#5cb885'
      } else if (monthlyCashFlow >= 0 && apprPct >= 2) {
        verdict = 'Decent Hold — Solid appreciation potential'; verdictColor = '#eab308'
      } else if (monthlyCashFlow < 0 && apprPct >= 3) {
        verdict = 'Speculative Hold — Relies on appreciation'; verdictColor = '#e8a44a'
      } else {
        verdict = 'Weak Hold — Insufficient returns'; verdictColor = '#ef4444'
      }

      return {
        strategy: 'hold' as const,
        cashInvested, downPayment, loanAmount, buyClosing,
        monthlyMortgage, totalMonthlyExpenses, monthlyCashFlow, annualCashFlow,
        cashOnCashReturn, annualNOI, capRate, projections, verdict, verdictColor,
        expenses: [
          { label: 'Mortgage (P&I)', amount: monthlyMortgage, color: '#5ba3d9' },
          { label: 'Property Tax', amount: monthlyTax, color: '#a855f7' },
          { label: 'Insurance', amount: monthlyIns, color: '#a855f7' },
          { label: `Maintenance (${maintPct}%)`, amount: monthlyMaint, color: '#e8a44a' },
          { label: `Vacancy (${vacPct}%)`, amount: monthlyVacancy, color: '#e8a44a' },
          { label: `Management (${mgmtP}%)`, amount: monthlyMgmt, color: '#ff7e5f' },
        ],
      }
    }

    /* ─── BRRRR ───────────────────────────────── */
    // Buy, Rehab, Rent, Refinance, Repeat
    const totalAcquisitionCost = pp + rehab + pp * (closingPct / 100)
    const initialCashIn = totalAcquisitionCost // Assume cash or hard money for initial purchase

    // After rehab, property is worth ARV
    // Rent it out
    const monthlyTax = taxAnnual / 12
    const monthlyIns = insAnnual / 12
    const monthlyMaint = rent * (maintPct / 100)
    const monthlyVacancy = rent * (vacPct / 100)
    const monthlyMgmt = rent * (mgmtP / 100)

    // Refinance based on ARV
    const refinanceAmount = arvN * (refiLtv / 100)
    const refinanceClosing = refinanceAmount * 0.02 // ~2% refi closing costs
    const cashOutFromRefi = refinanceAmount - refinanceClosing
    const moneyLeftInDeal = totalAcquisitionCost - cashOutFromRefi
    const monthlyRefiPayment = monthlyPayment(refinanceAmount, refiRate, refiYears)

    const totalMonthlyExpenses = monthlyRefiPayment + monthlyTax + monthlyIns + monthlyMaint + monthlyVacancy + monthlyMgmt
    const monthlyCashFlow = rent - totalMonthlyExpenses
    const annualCashFlow = monthlyCashFlow * 12
    const annualNOI = (rent * 12) - (monthlyTax * 12) - (monthlyIns * 12) - (monthlyMaint * 12) - (monthlyVacancy * 12) - (monthlyMgmt * 12)

    // Cash-on-cash based on money left in deal
    const cashOnCash = moneyLeftInDeal > 0 ? annualCashFlow / moneyLeftInDeal : (annualCashFlow > 0 ? Infinity : 0)
    const infiniteReturn = moneyLeftInDeal <= 0 && annualCashFlow > 0
    const capRate = pp > 0 ? annualNOI / pp : 0

    let verdict = ''
    let verdictColor = ''
    if (moneyLeftInDeal <= 0 && monthlyCashFlow > 0) {
      verdict = 'Home Run BRRRR — All cash out + positive cash flow'; verdictColor = '#5cb885'
    } else if (moneyLeftInDeal <= initialCashIn * 0.3 && monthlyCashFlow > 0) {
      verdict = 'Strong BRRRR — Most cash recovered + cash flow'; verdictColor = '#5cb885'
    } else if (monthlyCashFlow > 0) {
      verdict = 'Decent BRRRR — Positive cash flow'; verdictColor = '#eab308'
    } else {
      verdict = 'Weak BRRRR — Negative cash flow after refinance'; verdictColor = '#ef4444'
    }

    return {
      strategy: 'brrrr' as const,
      totalAcquisitionCost, initialCashIn, refinanceAmount, refinanceClosing,
      cashOutFromRefi, moneyLeftInDeal, monthlyRefiPayment,
      monthlyTax, monthlyIns, monthlyMaint, monthlyVacancy, monthlyMgmt,
      totalMonthlyExpenses, monthlyCashFlow, annualCashFlow, annualNOI,
      cashOnCash, infiniteReturn, capRate, verdict, verdictColor,
      expenses: [
        { label: 'Refinance Mortgage (P&I)', amount: monthlyRefiPayment, color: '#5ba3d9' },
        { label: 'Property Tax', amount: monthlyTax, color: '#a855f7' },
        { label: 'Insurance', amount: monthlyIns, color: '#a855f7' },
        { label: `Maintenance (${maintPct}%)`, amount: monthlyMaint, color: '#e8a44a' },
        { label: `Vacancy (${vacPct}%)`, amount: monthlyVacancy, color: '#e8a44a' },
        { label: `Management (${mgmtP}%)`, amount: monthlyMgmt, color: '#ff7e5f' },
      ],
    }
  }, [strategy, pp, arvN, rehab, closingPct, holdMo, realtorP, sellClosePct, finCostPct,
    rent, dpPct, intRate, loanYears, taxAnnual, insAnnual, maintPct, vacPct, mgmtP, apprPct,
    refiLtv, refiRate, refiYears, seasonMo])

  function handleReset() {
    setPurchasePrice(''); setArv(''); setRehabCost(''); setAddress('')
    setMonthlyRent(''); setPropertyTaxAnnual(''); setInsuranceAnnual('')
    setCalculated(false)
  }

  function handleDownload() {
    const r = results
    const lines: string[] = []
    if (r.strategy === 'flip') {
      lines.push(
        'STRATEGY: Fix & Flip',
        `Address: ${address || '(not entered)'}`,
        `Purchase Price: ${fmt(pp)}`,
        `ARV: ${fmt(arvN)}`,
        `Rehab: ${fmt(rehab)}`,
        '',
        'COST BREAKDOWN',
        ...r.costs.map(c => `  ${c.label}: ${fmt(c.amount)}`),
        `  Total Investment: ${fmt(r.totalInvestment)}`,
        '',
        'RETURNS',
        `  Net Profit: ${fmt(r.netProfit)}`,
        `  ROI: ${pct(r.roi)}`,
        `  Annualized ROI: ${pct(r.annualizedRoi)}`,
        `  Profit/Month: ${fmt(r.profitPerMonth)}`,
        '',
        `VERDICT: ${r.verdict}`,
      )
    } else if (r.strategy === 'rent') {
      lines.push(
        'STRATEGY: Buy & Rent',
        `Address: ${address || '(not entered)'}`,
        `Purchase Price: ${fmt(pp)}`,
        `Monthly Rent: ${fmt(rent)}`,
        `Cash Invested: ${fmt(r.cashInvested)}`,
        '',
        'MONTHLY EXPENSES',
        ...r.expenses.map(e => `  ${e.label}: ${fmt(e.amount)}`),
        `  Total Expenses: ${fmt(r.totalMonthlyExpenses)}`,
        '',
        'RETURNS',
        `  Monthly Cash Flow: ${fmt(r.monthlyCashFlow)}`,
        `  Annual Cash Flow: ${fmt(r.annualCashFlow)}`,
        `  Cash-on-Cash Return: ${pct(r.cashOnCashReturn)}`,
        `  Cap Rate: ${pct(r.capRate)}`,
        `  DSCR: ${r.dscr.toFixed(2)}`,
        '',
        `VERDICT: ${r.verdict}`,
      )
    } else if (r.strategy === 'hold') {
      lines.push(
        'STRATEGY: Buy & Hold',
        `Address: ${address || '(not entered)'}`,
        `Purchase Price: ${fmt(pp)}`,
        `Monthly Rent: ${fmt(rent)}`,
        `Appreciation Rate: ${apprPct}%`,
        '',
        'MONTHLY CASH FLOW',
        `  Gross Rent: ${fmt(rent)}`,
        ...r.expenses.map(e => `  ${e.label}: -${fmt(e.amount)}`),
        `  Net Cash Flow: ${fmt(r.monthlyCashFlow)}`,
        '',
        'WEALTH BUILDING PROJECTIONS',
        ...r.projections.map(p => `  Year ${p.year}: Equity ${fmt(p.equity)} | Cash Flow ${fmt(p.totalCashFlow)} | Total Return ${fmt(p.totalReturn)}`),
        '',
        `VERDICT: ${r.verdict}`,
      )
    } else {
      lines.push(
        'STRATEGY: BRRRR',
        `Address: ${address || '(not entered)'}`,
        `Purchase Price: ${fmt(pp)}`,
        `ARV: ${fmt(arvN)}`,
        `Rehab: ${fmt(rehab)}`,
        `Monthly Rent: ${fmt(rent)}`,
        '',
        'ACQUISITION',
        `  Total Acquisition Cost: ${fmt(r.totalAcquisitionCost)}`,
        '',
        'REFINANCE',
        `  Refinance Amount (${refiLtv}% LTV): ${fmt(r.refinanceAmount)}`,
        `  Refinance Closing Costs: ${fmt(r.refinanceClosing)}`,
        `  Cash Out: ${fmt(r.cashOutFromRefi)}`,
        `  Money Left in Deal: ${fmt(Math.max(0, r.moneyLeftInDeal))}`,
        '',
        'MONTHLY EXPENSES',
        ...r.expenses.map(e => `  ${e.label}: ${fmt(e.amount)}`),
        `  Total Expenses: ${fmt(r.totalMonthlyExpenses)}`,
        '',
        'RETURNS',
        `  Monthly Cash Flow: ${fmt(r.monthlyCashFlow)}`,
        `  Annual Cash Flow: ${fmt(r.annualCashFlow)}`,
        `  Cash-on-Cash: ${r.infiniteReturn ? '∞ (all cash recovered)' : pct(r.cashOnCash)}`,
        '',
        `VERDICT: ${r.verdict}`,
      )
    }
    downloadReport(`${STRATEGIES.find(s => s.id === strategy)!.label} Analysis`, lines)
  }

  const canCalculate = strategy === 'flip'
    ? pp > 0 && arvN > 0
    : strategy === 'brrrr'
      ? pp > 0 && arvN > 0 && rent > 0
      : pp > 0 && rent > 0

  const activeStrat = STRATEGIES.find(s => s.id === strategy)!

  return (
    <div>
      <h2 className="section-header">Multi-Strategy Investment Calculator</h2>
      <p style={{ color: '#888', fontSize: 14, marginBottom: 8, lineHeight: 1.7 }}>
        Analyze any deal across four investment strategies — Flip, Rent, Hold, and BRRRR. Compare returns and pick the best exit strategy.
      </p>

      <div className="info-tip" style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
          <Lightbulb size={14} color="#5cb885" />
          <span style={{ fontSize: 11, fontWeight: 700, color: '#5cb885', letterSpacing: '0.05em' }}>TIP</span>
        </div>
        <div style={{ fontSize: 13, color: '#ccc', lineHeight: 1.6 }}>
          Enter the same property and switch between strategies to compare which exit strategy maximizes your returns. Use real comps for ARV and get contractor quotes for rehab.
        </div>
      </div>

      {/* ── Strategy Selector ── */}
      <div style={{
        display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 10, marginBottom: 24,
      }}>
        {STRATEGIES.map(s => {
          const Icon = s.icon
          const active = strategy === s.id
          return (
            <button
              key={s.id}
              onClick={() => { setStrategy(s.id); setCalculated(false) }}
              style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6,
                padding: '16px 12px', borderRadius: 10, cursor: 'pointer',
                background: active ? 'rgba(244,126,95,0.10)' : '#263040',
                border: `2px solid ${active ? '#ff7e5f' : '#3d4e65'}`,
                color: active ? '#ff7e5f' : '#888',
                transition: 'all 0.2s',
                fontFamily: "'DM Sans', sans-serif",
              }}
            >
              <Icon size={22} />
              <span style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, letterSpacing: '0.04em' }}>
                {s.label}
              </span>
              <span style={{ fontSize: 11, color: active ? '#ccc' : '#666', textAlign: 'center', lineHeight: 1.4 }}>
                {s.desc}
              </span>
            </button>
          )
        })}
      </div>

      {/* ── Input Section ── */}
      <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
          <activeStrat.icon size={20} color="#ff7e5f" />
          <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 22, color: '#ff7e5f', letterSpacing: '0.04em', margin: 0 }}>
            {activeStrat.label} — Deal Inputs
          </h3>
        </div>

        {/* Property info */}
        <div style={{ marginBottom: 16 }}>
          <Field label="Property Address (optional)" icon={Home}>
            <input className="input-dark" placeholder="123 Main St, Atlanta, GA" value={address} onChange={e => setAddress(e.target.value)} />
          </Field>
        </div>

        {/* Core numbers */}
        <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 16, marginBottom: 20 }}>
          <Field label="Purchase Price" icon={DollarSign} required color="#ff7e5f">
            <input className="input-dark" type="number" placeholder="200000" value={purchasePrice} onChange={e => setPurchasePrice(e.target.value)}
              style={{ borderColor: pp > 0 ? '#5cb885' : undefined }} />
          </Field>

          {(strategy === 'flip' || strategy === 'brrrr') && (
            <Field label="After Repair Value (ARV)" icon={TrendingUp} required color="#ff7e5f">
              <input className="input-dark" type="number" placeholder="300000" value={arv} onChange={e => setArv(e.target.value)}
                style={{ borderColor: arvN > 0 ? '#5cb885' : undefined }} />
            </Field>
          )}

          <Field label="Rehab / Repair Cost" icon={Wrench} color="#ffb347">
            <input className="input-dark" type="number" placeholder="40000" value={rehabCost} onChange={e => setRehabCost(e.target.value)} />
          </Field>

          {strategy !== 'flip' && (
            <Field label="Monthly Rent" icon={DollarSign} required color="#ff7e5f">
              <input className="input-dark" type="number" placeholder="2000" value={monthlyRent} onChange={e => setMonthlyRent(e.target.value)}
                style={{ borderColor: rent > 0 ? '#5cb885' : undefined }} />
            </Field>
          )}
        </div>

        {/* Strategy-specific inputs */}
        {strategy === 'flip' && (
          <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16, marginBottom: 20 }}>
            <Field label="Holding Period (months)" icon={Calculator}>
              <input className="input-dark" type="number" placeholder="6" value={holdingMonths} onChange={e => setHoldingMonths(e.target.value)} />
            </Field>
            <Field label="Realtor Commission %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="5" value={realtorPct} onChange={e => setRealtorPct(e.target.value)} />
            </Field>
            <Field label="Financing APR %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="12" value={financingCostPct} onChange={e => setFinancingCostPct(e.target.value)} />
            </Field>
            <Field label="Buying Closing Cost %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="3" value={closingCostPct} onChange={e => setClosingCostPct(e.target.value)} />
            </Field>
          </div>
        )}

        {(strategy === 'rent' || strategy === 'hold') && (
          <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16, marginBottom: 20 }}>
            <Field label="Down Payment %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="20" value={downPaymentPct} onChange={e => setDownPaymentPct(e.target.value)} />
            </Field>
            <Field label="Interest Rate %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="7" value={interestRate} onChange={e => setInterestRate(e.target.value)} />
            </Field>
            <Field label="Loan Term (years)" icon={Calculator}>
              <input className="input-dark" type="number" placeholder="30" value={loanTermYears} onChange={e => setLoanTermYears(e.target.value)} />
            </Field>
            <Field label="Closing Cost %" icon={Percent}>
              <input className="input-dark" type="number" placeholder="3" value={closingCostPct} onChange={e => setClosingCostPct(e.target.value)} />
            </Field>
          </div>
        )}

        {strategy === 'brrrr' && (
          <>
            <div style={{ fontSize: 13, color: '#ffb347', fontWeight: 600, marginBottom: 12, marginTop: 8 }}>Initial Purchase (Cash / Hard Money)</div>
            <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16, marginBottom: 20 }}>
              <Field label="Closing Cost %" icon={Percent}>
                <input className="input-dark" type="number" placeholder="3" value={closingCostPct} onChange={e => setClosingCostPct(e.target.value)} />
              </Field>
              <Field label="Seasoning Period (months)" icon={Calculator}>
                <input className="input-dark" type="number" placeholder="6" value={seasoning} onChange={e => setSeasoning(e.target.value)} />
              </Field>
            </div>
            <div style={{ fontSize: 13, color: '#5ba3d9', fontWeight: 600, marginBottom: 12 }}>Refinance Terms</div>
            <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16, marginBottom: 20 }}>
              <Field label="Refinance LTV %" icon={Percent}>
                <input className="input-dark" type="number" placeholder="75" value={refinanceLtv} onChange={e => setRefinanceLtv(e.target.value)} />
              </Field>
              <Field label="Refinance Rate %" icon={Percent}>
                <input className="input-dark" type="number" placeholder="7" value={refinanceRate} onChange={e => setRefinanceRate(e.target.value)} />
              </Field>
              <Field label="Refinance Term (years)" icon={Calculator}>
                <input className="input-dark" type="number" placeholder="30" value={refinanceTermYears} onChange={e => setRefinanceTermYears(e.target.value)} />
              </Field>
            </div>
          </>
        )}

        {/* Advanced: Operating Expenses (for rent, hold, brrrr) */}
        {strategy !== 'flip' && (
          <>
            <button
              onClick={() => setShowAdvanced(!showAdvanced)}
              style={{
                display: 'flex', alignItems: 'center', gap: 6,
                background: 'none', border: 'none', cursor: 'pointer',
                color: '#888', fontSize: 13, marginBottom: showAdvanced ? 16 : 0,
                fontFamily: "'DM Sans', sans-serif",
              }}
            >
              {showAdvanced ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              Operating Expenses
            </button>
            {showAdvanced && (
              <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16 }}>
                <Field label="Property Tax (annual)" icon={DollarSign}>
                  <input className="input-dark" type="number" placeholder="3000" value={propertyTaxAnnual} onChange={e => setPropertyTaxAnnual(e.target.value)} />
                </Field>
                <Field label="Insurance (annual)" icon={DollarSign}>
                  <input className="input-dark" type="number" placeholder="1500" value={insuranceAnnual} onChange={e => setInsuranceAnnual(e.target.value)} />
                </Field>
                <Field label="Maintenance Reserve %" icon={Percent}>
                  <input className="input-dark" type="number" placeholder="5" value={maintenancePct} onChange={e => setMaintenancePct(e.target.value)} />
                </Field>
                <Field label="Vacancy Rate %" icon={Percent}>
                  <input className="input-dark" type="number" placeholder="8" value={vacancyPct} onChange={e => setVacancyPct(e.target.value)} />
                </Field>
                <Field label="Property Mgmt %" icon={Percent}>
                  <input className="input-dark" type="number" placeholder="10" value={mgmtPct} onChange={e => setMgmtPct(e.target.value)} />
                </Field>
                {strategy === 'hold' && (
                  <Field label="Annual Appreciation %" icon={TrendingUp}>
                    <input className="input-dark" type="number" placeholder="3" value={appreciationPct} onChange={e => setAppreciationPct(e.target.value)} />
                  </Field>
                )}
              </div>
            )}
          </>
        )}

        {/* Buttons */}
        <div style={{ display: 'flex', gap: 12, marginTop: 24, flexWrap: 'wrap' }}>
          <button onClick={() => setCalculated(true)} disabled={!canCalculate} className="btn-orange"
            style={{ padding: '14px 32px', fontSize: 16, opacity: canCalculate ? 1 : 0.5 }}>
            <Calculator size={16} /> Analyze Deal
          </button>
          <button onClick={handleReset} className="btn-ghost" style={{ padding: '14px 20px', fontSize: 14 }}>
            <RotateCcw size={14} /> Reset
          </button>
        </div>
      </div>

      {/* ══════════════════════════════════════════ */}
      {/* ── RESULTS ──────────────────────────────── */}
      {/* ══════════════════════════════════════════ */}
      {calculated && canCalculate && (
        <div style={{ animation: 'fadeInUp 0.4s ease' }}>

          {/* ── FLIP RESULTS ── */}
          {results.strategy === 'flip' && (() => {
            const r = results
            return (
              <>
                {/* Key metrics */}
                <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 12, marginBottom: 24 }}>
                  <MetricCard label="Sale Price (ARV)" value={fmt(arvN)} color="#5ba3d9" />
                  <MetricCard label="Total Investment" value={fmt(r.totalInvestment)} color="#ffb347" />
                  <MetricCard label="Net Profit" value={fmt(r.netProfit)} color={r.netProfit >= 0 ? '#5cb885' : '#ef4444'} />
                  <MetricCard label="ROI" value={pct(r.roi)} color={r.roi >= 0.15 ? '#5cb885' : '#e8a44a'} />
                  <MetricCard label="Annualized ROI" value={pct(r.annualizedRoi)} color="#a855f7" />
                  <MetricCard label="Profit / Month" value={fmt(r.profitPerMonth)} color="#ffb347" sub={`over ${holdMo} months`} />
                </div>

                {/* Verdict */}
                <div style={{
                  background: `${r.verdictColor}10`, border: `1px solid ${r.verdictColor}40`,
                  borderRadius: 10, padding: '16px 20px', marginBottom: 24,
                  display: 'flex', alignItems: 'center', gap: 12,
                }}>
                  {r.roi >= 0.10 ? <CheckCircle2 size={22} color={r.verdictColor} /> : <AlertTriangle size={22} color={r.verdictColor} />}
                  <div>
                    <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, color: r.verdictColor, letterSpacing: '0.04em' }}>
                      {r.verdict}
                    </div>
                    <div style={{ fontSize: 12, color: '#888', marginTop: 2 }}>
                      Net Profit: {fmt(r.netProfit)} | ROI: {pct(r.roi)} | Holding: {holdMo} months
                    </div>
                  </div>
                </div>

                {/* Cost breakdown */}
                <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347', letterSpacing: '0.04em', margin: '0 0 16px' }}>
                    Full Cost Breakdown
                  </h3>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {r.costs.map((c, i) => <CostLine key={i} label={c.label} amount={c.amount} dotColor={c.color} />)}
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: '#3d4e65', borderRadius: 6, marginTop: 4,
                    }}>
                      <span style={{ fontSize: 14, color: '#ff7e5f', fontWeight: 700 }}>Total Investment</span>
                      <span style={{ fontSize: 16, color: '#ff7e5f', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.totalInvestment)}</span>
                    </div>
                  </div>
                </div>
              </>
            )
          })()}

          {/* ── RENT RESULTS ── */}
          {results.strategy === 'rent' && (() => {
            const r = results
            return (
              <>
                {/* Key metrics */}
                <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 12, marginBottom: 24 }}>
                  <MetricCard label="Cash Invested" value={fmt(r.cashInvested)} color="#5ba3d9" />
                  <MetricCard label="Monthly Cash Flow" value={fmt(r.monthlyCashFlow)} color={r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444'} />
                  <MetricCard label="Annual Cash Flow" value={fmt(r.annualCashFlow)} color={r.annualCashFlow >= 0 ? '#5cb885' : '#ef4444'} />
                  <MetricCard label="Cash-on-Cash" value={pct(r.cashOnCashReturn)} color={r.cashOnCashReturn >= 0.08 ? '#5cb885' : '#e8a44a'} />
                  <MetricCard label="Cap Rate" value={pct(r.capRate)} color="#a855f7" />
                  <MetricCard label="DSCR" value={r.dscr.toFixed(2)} color={r.dscr >= 1.25 ? '#5cb885' : '#e8a44a'} sub={r.dscr >= 1.25 ? 'Healthy' : 'Tight'} />
                </div>

                {/* Verdict */}
                <div style={{
                  background: `${r.verdictColor}10`, border: `1px solid ${r.verdictColor}40`,
                  borderRadius: 10, padding: '16px 20px', marginBottom: 24,
                  display: 'flex', alignItems: 'center', gap: 12,
                }}>
                  {r.monthlyCashFlow >= 100 ? <CheckCircle2 size={22} color={r.verdictColor} /> : <AlertTriangle size={22} color={r.verdictColor} />}
                  <div>
                    <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, color: r.verdictColor }}>{r.verdict}</div>
                    <div style={{ fontSize: 12, color: '#888', marginTop: 2 }}>
                      Cash Flow: {fmt(r.monthlyCashFlow)}/mo | CoC: {pct(r.cashOnCashReturn)} | GRM: {r.grm.toFixed(1)}
                    </div>
                  </div>
                </div>

                {/* Monthly expense breakdown */}
                <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347', letterSpacing: '0.04em', margin: '0 0 4px' }}>
                    Monthly Expense Breakdown
                  </h3>
                  <p style={{ fontSize: 12, color: '#666', margin: '0 0 16px' }}>Gross Rent: {fmt(rent)}/mo</p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {r.expenses.map((e, i) => <CostLine key={i} label={e.label} amount={e.amount} dotColor={e.color} />)}
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: '#3d4e65', borderRadius: 6, marginTop: 4,
                    }}>
                      <span style={{ fontSize: 14, color: '#ff7e5f', fontWeight: 700 }}>Total Monthly Expenses</span>
                      <span style={{ fontSize: 16, color: '#ff7e5f', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.totalMonthlyExpenses)}</span>
                    </div>
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.08)' : 'rgba(239,68,68,0.08)',
                      border: `1px solid ${r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.3)' : 'rgba(239,68,68,0.3)'}`,
                      borderRadius: 6,
                    }}>
                      <span style={{ fontSize: 14, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700 }}>Net Monthly Cash Flow</span>
                      <span style={{ fontSize: 16, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.monthlyCashFlow)}</span>
                    </div>
                  </div>
                </div>

                {/* Key ratios */}
                <div style={{
                  background: 'linear-gradient(135deg, rgba(244,126,95,0.08), rgba(255,179,71,0.04))',
                  border: '1px solid rgba(244,126,95,0.2)', borderRadius: 10, padding: 24, marginBottom: 24,
                }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ff7e5f', margin: '0 0 16px' }}>
                    Key Investment Ratios
                  </h3>
                  <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 12 }}>
                    <div style={{ background: '#263040', borderRadius: 8, padding: 14, textAlign: 'center' }}>
                      <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>NOI (Annual)</div>
                      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#5cb885' }}>{fmt(r.annualNOI)}</div>
                    </div>
                    <div style={{ background: '#263040', borderRadius: 8, padding: 14, textAlign: 'center' }}>
                      <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>Cap Rate</div>
                      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#a855f7' }}>{pct(r.capRate)}</div>
                    </div>
                    <div style={{ background: '#263040', borderRadius: 8, padding: 14, textAlign: 'center' }}>
                      <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>GRM</div>
                      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347' }}>{r.grm.toFixed(1)}</div>
                    </div>
                    <div style={{ background: '#263040', borderRadius: 8, padding: 14, textAlign: 'center' }}>
                      <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>DSCR</div>
                      <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: r.dscr >= 1.25 ? '#5cb885' : '#e8a44a' }}>{r.dscr.toFixed(2)}</div>
                    </div>
                  </div>
                </div>
              </>
            )
          })()}

          {/* ── HOLD RESULTS ── */}
          {results.strategy === 'hold' && (() => {
            const r = results
            return (
              <>
                {/* Key metrics */}
                <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))', gap: 12, marginBottom: 24 }}>
                  <MetricCard label="Cash Invested" value={fmt(r.cashInvested)} color="#5ba3d9" />
                  <MetricCard label="Monthly Cash Flow" value={fmt(r.monthlyCashFlow)} color={r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444'} />
                  <MetricCard label="Cash-on-Cash" value={pct(r.cashOnCashReturn)} color={r.cashOnCashReturn >= 0.08 ? '#5cb885' : '#e8a44a'} />
                  <MetricCard label="Cap Rate" value={pct(r.capRate)} color="#a855f7" />
                </div>

                {/* Verdict */}
                <div style={{
                  background: `${r.verdictColor}10`, border: `1px solid ${r.verdictColor}40`,
                  borderRadius: 10, padding: '16px 20px', marginBottom: 24,
                  display: 'flex', alignItems: 'center', gap: 12,
                }}>
                  {r.monthlyCashFlow >= 0 ? <CheckCircle2 size={22} color={r.verdictColor} /> : <AlertTriangle size={22} color={r.verdictColor} />}
                  <div>
                    <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, color: r.verdictColor }}>{r.verdict}</div>
                    <div style={{ fontSize: 12, color: '#888', marginTop: 2 }}>
                      Cash Flow: {fmt(r.monthlyCashFlow)}/mo | Appreciation: {apprPct}%/yr
                    </div>
                  </div>
                </div>

                {/* Monthly expenses */}
                <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347', margin: '0 0 4px' }}>Monthly Expenses</h3>
                  <p style={{ fontSize: 12, color: '#666', margin: '0 0 16px' }}>Gross Rent: {fmt(rent)}/mo</p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {r.expenses.map((e, i) => <CostLine key={i} label={e.label} amount={e.amount} dotColor={e.color} />)}
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.08)' : 'rgba(239,68,68,0.08)',
                      border: `1px solid ${r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.3)' : 'rgba(239,68,68,0.3)'}`,
                      borderRadius: 6, marginTop: 4,
                    }}>
                      <span style={{ fontSize: 14, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700 }}>Net Monthly Cash Flow</span>
                      <span style={{ fontSize: 16, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.monthlyCashFlow)}</span>
                    </div>
                  </div>
                </div>

                {/* Wealth building projections */}
                <div style={{
                  background: 'linear-gradient(135deg, rgba(91,163,217,0.06), rgba(168,85,247,0.04))',
                  border: '1px solid rgba(91,163,217,0.2)', borderRadius: 10, padding: 24, marginBottom: 24,
                }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#5ba3d9', margin: '0 0 4px' }}>
                    <TrendingUp size={18} style={{ display: 'inline', verticalAlign: '-3px', marginRight: 8 }} />
                    Wealth Building Projections
                  </h3>
                  <p style={{ fontSize: 12, color: '#666', margin: '0 0 16px' }}>Based on {apprPct}% annual appreciation</p>
                  <div style={{ overflowX: 'auto' }}>
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                      <thead>
                        <tr style={{ borderBottom: '1px solid #3d4e65' }}>
                          {['Year', 'Property Value', 'Equity', 'Total Cash Flow', 'Total Return', 'Ann. Return'].map(h => (
                            <th key={h} style={{ padding: '10px 12px', textAlign: 'right', color: '#888', fontSize: 11, fontWeight: 600, whiteSpace: 'nowrap' }}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {r.projections.map(p => (
                          <tr key={p.year} style={{ borderBottom: '1px solid rgba(47,58,74,0.5)' }}>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: '#ffb347', fontWeight: 600 }}>{p.year}</td>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: '#f5f0eb' }}>{fmt(p.futureValue)}</td>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: '#5cb885' }}>{fmt(p.equity)}</td>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: '#5ba3d9' }}>{fmt(p.totalCashFlow)}</td>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: p.totalReturn >= 0 ? '#5cb885' : '#ef4444', fontWeight: 600 }}>{fmt(p.totalReturn)}</td>
                            <td style={{ padding: '10px 12px', textAlign: 'right', color: '#a855f7' }}>{pct(p.annualizedReturn)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </>
            )
          })()}

          {/* ── BRRRR RESULTS ── */}
          {results.strategy === 'brrrr' && (() => {
            const r = results
            const cashRecoveredPct = r.initialCashIn > 0 ? r.cashOutFromRefi / r.initialCashIn : 0
            return (
              <>
                {/* BRRRR Flow Visual */}
                <div style={{
                  background: 'linear-gradient(135deg, rgba(244,126,95,0.06), rgba(91,163,217,0.04))',
                  border: '1px solid rgba(244,126,95,0.2)', borderRadius: 10, padding: 24, marginBottom: 24,
                }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ff7e5f', margin: '0 0 16px' }}>
                    <RefreshCw size={18} style={{ display: 'inline', verticalAlign: '-3px', marginRight: 8 }} />
                    BRRRR Breakdown
                  </h3>
                  <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))', gap: 12 }}>
                    <MetricCard label="Buy + Rehab + Closing" value={fmt(r.totalAcquisitionCost)} color="#ff7e5f" sub="Total cash in" />
                    <MetricCard label="ARV (After Rehab)" value={fmt(arvN)} color="#5ba3d9" sub="Appraised value" />
                    <MetricCard label={`Refinance (${refiLtv}% LTV)`} value={fmt(r.refinanceAmount)} color="#a855f7" sub="New loan amount" />
                    <MetricCard label="Cash Recovered" value={fmt(r.cashOutFromRefi)} color="#5cb885" sub={pct(cashRecoveredPct) + ' recovered'} />
                    <MetricCard label="Money Left in Deal" value={r.moneyLeftInDeal <= 0 ? '$0' : fmt(r.moneyLeftInDeal)}
                      color={r.moneyLeftInDeal <= 0 ? '#5cb885' : '#ffb347'}
                      sub={r.moneyLeftInDeal <= 0 ? 'All cash out!' : 'Still invested'} />
                    <MetricCard label="Monthly Cash Flow" value={fmt(r.monthlyCashFlow)}
                      color={r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444'} sub="After refinance" />
                  </div>
                </div>

                {/* Verdict */}
                <div style={{
                  background: `${r.verdictColor}10`, border: `1px solid ${r.verdictColor}40`,
                  borderRadius: 10, padding: '16px 20px', marginBottom: 24,
                  display: 'flex', alignItems: 'center', gap: 12,
                }}>
                  {r.monthlyCashFlow > 0 && r.moneyLeftInDeal <= r.initialCashIn * 0.3
                    ? <CheckCircle2 size={22} color={r.verdictColor} />
                    : <AlertTriangle size={22} color={r.verdictColor} />}
                  <div>
                    <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, color: r.verdictColor }}>{r.verdict}</div>
                    <div style={{ fontSize: 12, color: '#888', marginTop: 2 }}>
                      Cash Flow: {fmt(r.monthlyCashFlow)}/mo | Cash-on-Cash: {r.infiniteReturn ? '∞' : pct(r.cashOnCash)} | Cap Rate: {pct(r.capRate)}
                    </div>
                  </div>
                </div>

                {/* Monthly expense breakdown */}
                <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
                  <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347', margin: '0 0 4px' }}>
                    Monthly Expenses (After Refinance)
                  </h3>
                  <p style={{ fontSize: 12, color: '#666', margin: '0 0 16px' }}>Gross Rent: {fmt(rent)}/mo</p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {r.expenses.map((e, i) => <CostLine key={i} label={e.label} amount={e.amount} dotColor={e.color} />)}
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: '#3d4e65', borderRadius: 6, marginTop: 4,
                    }}>
                      <span style={{ fontSize: 14, color: '#ff7e5f', fontWeight: 700 }}>Total Monthly Expenses</span>
                      <span style={{ fontSize: 16, color: '#ff7e5f', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.totalMonthlyExpenses)}</span>
                    </div>
                    <div style={{
                      display: 'flex', justifyContent: 'space-between', padding: '12px 14px',
                      background: r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.08)' : 'rgba(239,68,68,0.08)',
                      border: `1px solid ${r.monthlyCashFlow >= 0 ? 'rgba(92,184,133,0.3)' : 'rgba(239,68,68,0.3)'}`,
                      borderRadius: 6,
                    }}>
                      <span style={{ fontSize: 14, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700 }}>Net Monthly Cash Flow</span>
                      <span style={{ fontSize: 16, color: r.monthlyCashFlow >= 0 ? '#5cb885' : '#ef4444', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif" }}>{fmt(r.monthlyCashFlow)}</span>
                    </div>
                  </div>
                </div>

                {/* Seasoning note */}
                <div className="info-warn" style={{ marginBottom: 24 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
                    <AlertTriangle size={14} color="#e8a44a" />
                    <span style={{ fontSize: 11, fontWeight: 700, color: '#e8a44a', letterSpacing: '0.05em' }}>SEASONING PERIOD</span>
                  </div>
                  <div style={{ fontSize: 13, color: '#ccc', lineHeight: 1.6 }}>
                    Most lenders require a <strong>{seasonMo}-month seasoning period</strong> before they&apos;ll refinance based on the new appraised value. During this time, you&apos;ll need to cover holding costs from rental income or reserves. Budget {fmt(r.totalMonthlyExpenses * seasonMo)} for {seasonMo} months of expenses.
                  </div>
                </div>
              </>
            )
          })()}

          {/* Download */}
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <button onClick={handleDownload} className="btn-orange" style={{ padding: '12px 24px', fontSize: 14 }}>
              <Download size={14} /> Download Analysis
            </button>
          </div>
        </div>
      )}

      {/* Empty state */}
      {!calculated && (
        <div style={{
          textAlign: 'center', padding: '40px 20px', color: '#555',
          background: '#263040', border: '1px solid #3d4e65', borderRadius: 10,
        }}>
          <activeStrat.icon size={32} color="#333" style={{ marginBottom: 12 }} />
          <p style={{ fontSize: 14, margin: 0 }}>
            Enter the deal details above and hit <strong>Analyze Deal</strong> to see your {activeStrat.label} returns.
          </p>
        </div>
      )}
    </div>
  )
}
