import { useState } from 'react'
import {
  Calculator, DollarSign, TrendingUp, Home, Wrench,
  Target, ChevronDown, ChevronUp, Download, AlertTriangle,
  CheckCircle2, Lightbulb, Percent, PiggyBank,
} from 'lucide-react'

function fmt(n: number) {
  if (!n && n !== 0) return '$0'
  return '$' + Math.round(n).toLocaleString('en-US')
}

function pct(n: number) {
  return (n * 100).toFixed(1) + '%'
}

interface CostItem {
  label: string
  amount: number
  category: 'closing' | 'holding' | 'rehab' | 'fee'
}

function downloadOfferSheet(data: OfferData) {
  const text = `WHOLESALE DEAL ANALYSIS — QUICK OFFER SHEET
Generated: ${new Date().toLocaleDateString()}

PROPERTY INFORMATION
Address: ${data.address || '(not entered)'}
City/State: ${data.cityState || '(not entered)'}

ESTIMATED VALUES
After Repair Value (ARV): ${fmt(data.arv)}
Estimated Repairs: ${fmt(data.repairs)}
Your Assignment Fee: ${fmt(data.assignmentFee)}

OFFER CALCULATION (${data.rulePct}% Rule)
Formula: ARV × ${data.rulePct}% − Repairs − Assignment Fee
${fmt(data.arv)} × ${data.rulePct}% = ${fmt(data.arv * data.rulePct / 100)}
Less Repairs: −${fmt(data.repairs)}
Less Assignment Fee: −${fmt(data.assignmentFee)}

MAXIMUM ALLOWABLE OFFER (MAO): ${fmt(data.mao)}

DETAILED COST BREAKDOWN
${data.costs.map(c => `  ${c.label}: ${fmt(c.amount)}`).join('\n')}
Total Costs: ${fmt(data.totalCosts)}

INVESTOR'S NUMBERS
Purchase Price (MAO): ${fmt(data.mao)}
Total Investment: ${fmt(data.totalInvestment)}
Sale Price (ARV): ${fmt(data.arv)}
Investor Gross Profit: ${fmt(data.investorProfit)}
Investor ROI: ${pct(data.investorROI)}

YOUR WHOLESALE PROFIT
Assignment Fee: ${fmt(data.assignmentFee)}

OFFER RANGE
Conservative (${data.rulePct - 5}%): ${fmt(data.conservativeOffer)}
Standard (${data.rulePct}%): ${fmt(data.mao)}
Aggressive (${data.rulePct + 5}%): ${fmt(data.aggressiveOffer)}

DEAL VERDICT: ${data.verdict}

---
Generated by Flip the Contract — Quick Offer Calculator
For educational purposes only. Always verify with your own due diligence.
© 2026 Flip the Contract. All rights reserved.`
  const blob = new Blob([text], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `Offer_Sheet_${data.address?.replace(/\s+/g, '_') || 'Deal'}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

interface OfferData {
  address: string
  cityState: string
  arv: number
  repairs: number
  assignmentFee: number
  rulePct: number
  mao: number
  conservativeOffer: number
  aggressiveOffer: number
  costs: CostItem[]
  totalCosts: number
  totalInvestment: number
  investorProfit: number
  investorROI: number
  verdict: string
}

export default function QuickOfferCalc() {
  const [address, setAddress] = useState('')
  const [cityState, setCityState] = useState('')
  const [arv, setArv] = useState('')
  const [repairs, setRepairs] = useState('')
  const [assignmentFee, setAssignmentFee] = useState('10000')
  const [rulePct, setRulePct] = useState('70')
  const [holdingMonths, setHoldingMonths] = useState('6')
  const [closingCostPct, setClosingCostPct] = useState('3')
  const [showAdvanced, setShowAdvanced] = useState(false)
  const [calculated, setCalculated] = useState(false)

  const arvN = parseFloat(arv) || 0
  const repN = parseFloat(repairs) || 0
  const feeN = parseFloat(assignmentFee) || 0
  const ruleN = parseFloat(rulePct) || 70
  const holdN = parseFloat(holdingMonths) || 6
  const closingN = parseFloat(closingCostPct) || 3

  // Calculate MAO
  const mao = arvN * (ruleN / 100) - repN - feeN
  const conservativeOffer = arvN * ((ruleN - 5) / 100) - repN - feeN
  const aggressiveOffer = arvN * ((ruleN + 5) / 100) - repN - feeN

  // Detailed cost breakdown for investor
  const buyerClosingCosts = mao * (closingN / 100)
  const sellerClosingCosts = arvN * 0.02 // 2% selling closing costs
  const realtorCommission = arvN * 0.05 // 5% agent commission on resale
  const holdingCosts = mao * 0.01 * holdN // ~1% per month (insurance, taxes, utilities)
  const financingCosts = mao * 0.005 * holdN // hard money interest ~6%/yr

  const costs: CostItem[] = [
    { label: 'Buyer Closing Costs', amount: buyerClosingCosts, category: 'closing' },
    { label: 'Rehab / Repairs', amount: repN, category: 'rehab' },
    { label: 'Holding Costs (insurance, taxes, utilities)', amount: holdingCosts, category: 'holding' },
    { label: 'Financing Costs (hard money interest)', amount: financingCosts, category: 'holding' },
    { label: 'Selling Closing Costs', amount: sellerClosingCosts, category: 'closing' },
    { label: 'Realtor Commission (resale)', amount: realtorCommission, category: 'closing' },
    { label: 'Your Assignment Fee', amount: feeN, category: 'fee' },
  ]

  const totalCosts = costs.reduce((s, c) => s + c.amount, 0)
  const totalInvestment = mao + totalCosts - feeN // fee already accounted in MAO
  const investorProfit = arvN - totalInvestment
  const investorROI = totalInvestment > 0 ? investorProfit / totalInvestment : 0

  let verdict = ''
  let verdictColor = ''
  if (arvN > 0 && repN >= 0) {
    if (investorROI >= 0.20) {
      verdict = 'Strong Deal — Good margins for your buyer'
      verdictColor = '#5cb885'
    } else if (investorROI >= 0.10) {
      verdict = 'Decent Deal — Tight margins, experienced buyers only'
      verdictColor = '#eab308'
    } else if (investorROI > 0) {
      verdict = 'Thin Deal — Very tight margins, may be hard to assign'
      verdictColor = '#e8a44a'
    } else {
      verdict = 'No Deal — Numbers don\'t work at this price'
      verdictColor = '#ef4444'
    }
  }

  function handleCalculate() {
    setCalculated(true)
  }

  const offerData: OfferData = {
    address, cityState, arv: arvN, repairs: repN, assignmentFee: feeN,
    rulePct: ruleN, mao, conservativeOffer, aggressiveOffer,
    costs, totalCosts, totalInvestment, investorProfit, investorROI, verdict,
  }

  return (
    <div>
      <h2 className="section-header">Quick Offer Calculator</h2>
      <p style={{ color: '#888', fontSize: 14, marginBottom: 8, lineHeight: 1.7 }}>
        Generate instant wholesale offers with a full cost breakdown. Know your numbers before you make the call.
      </p>

      <div className="info-tip" style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
          <Lightbulb size={14} color="#5cb885" />
          <span style={{ fontSize: 11, fontWeight: 700, color: '#5cb885', letterSpacing: '0.05em' }}>TIP</span>
        </div>
        <div style={{ fontSize: 13, color: '#ccc', lineHeight: 1.6 }}>
          The 70% rule is the industry standard: <strong>MAO = ARV × 70% − Repairs − Your Fee</strong>. Adjust higher (75%) in competitive markets or lower (65%) for riskier deals.
        </div>
      </div>

      {/* Input Section */}
      <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20 }}>
          <Calculator size={20} color="#ff7e5f" />
          <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 22, color: '#ff7e5f', letterSpacing: '0.04em', margin: 0 }}>
            Deal Inputs
          </h3>
        </div>

        {/* Property info */}
        <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: 16, marginBottom: 20 }}>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#888', marginBottom: 6 }}>
              <Home size={12} /> Property Address (optional)
            </label>
            <input className="input-dark" placeholder="123 Main St" value={address} onChange={e => setAddress(e.target.value)} />
          </div>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#888', marginBottom: 6 }}>
              <Home size={12} /> City / State (optional)
            </label>
            <input className="input-dark" placeholder="Atlanta, GA" value={cityState} onChange={e => setCityState(e.target.value)} />
          </div>
        </div>

        {/* Core numbers */}
        <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 16, marginBottom: 20 }}>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#ff7e5f', marginBottom: 6, fontWeight: 600 }}>
              <TrendingUp size={12} /> After Repair Value (ARV) *
            </label>
            <input className="input-dark" type="number" placeholder="250000" value={arv} onChange={e => setArv(e.target.value)} style={{ borderColor: arvN > 0 ? '#5cb885' : undefined }} />
          </div>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#ff7e5f', marginBottom: 6, fontWeight: 600 }}>
              <Wrench size={12} /> Estimated Repairs *
            </label>
            <input className="input-dark" type="number" placeholder="35000" value={repairs} onChange={e => setRepairs(e.target.value)} style={{ borderColor: repN > 0 ? '#5cb885' : undefined }} />
          </div>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#ffb347', marginBottom: 6, fontWeight: 600 }}>
              <DollarSign size={12} /> Your Assignment Fee
            </label>
            <input className="input-dark" type="number" placeholder="10000" value={assignmentFee} onChange={e => setAssignmentFee(e.target.value)} />
          </div>
          <div>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#ffb347', marginBottom: 6, fontWeight: 600 }}>
              <Percent size={12} /> Rule Percentage
            </label>
            <div style={{ display: 'flex', gap: 6 }}>
              {[65, 70, 75, 80].map(p => (
                <button
                  key={p}
                  onClick={() => setRulePct(String(p))}
                  style={{
                    flex: 1,
                    padding: '10px 0',
                    borderRadius: 6,
                    border: `1px solid ${ruleN === p ? '#ff7e5f' : '#3d4e65'}`,
                    background: ruleN === p ? 'rgba(244,126,95,0.15)' : 'transparent',
                    color: ruleN === p ? '#ff7e5f' : '#888',
                    cursor: 'pointer',
                    fontSize: 14,
                    fontWeight: 600,
                    fontFamily: "'DM Sans', sans-serif",
                  }}
                >
                  {p}%
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Advanced toggle */}
        <button
          onClick={() => setShowAdvanced(!showAdvanced)}
          style={{
            display: 'flex', alignItems: 'center', gap: 6,
            background: 'none', border: 'none', cursor: 'pointer',
            color: '#888', fontSize: 13, marginBottom: showAdvanced ? 16 : 0,
            fontFamily: "'DM Sans', sans-serif",
          }}
        >
          {showAdvanced ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
          Advanced Settings
        </button>

        {showAdvanced && (
          <div className="offer-calc-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 16 }}>
            <div>
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#888', marginBottom: 6 }}>
                Holding Period (months)
              </label>
              <input className="input-dark" type="number" placeholder="6" value={holdingMonths} onChange={e => setHoldingMonths(e.target.value)} />
            </div>
            <div>
              <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#888', marginBottom: 6 }}>
                Buyer Closing Cost %
              </label>
              <input className="input-dark" type="number" placeholder="3" value={closingCostPct} onChange={e => setClosingCostPct(e.target.value)} />
            </div>
          </div>
        )}

        {/* Calculate button */}
        <button
          onClick={handleCalculate}
          disabled={arvN <= 0}
          className="btn-orange"
          style={{ marginTop: 24, padding: '14px 32px', fontSize: 16, opacity: arvN > 0 ? 1 : 0.5 }}
        >
          <Calculator size={16} /> Calculate Offer
        </button>
      </div>

      {/* Results */}
      {calculated && arvN > 0 && (
        <div style={{ animation: 'fadeInUp 0.4s ease' }}>
          {/* Offer Range Cards */}
          <div className="offer-range-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12, marginBottom: 24 }}>
            <div style={{
              background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 20,
              textAlign: 'center', opacity: 0.8,
            }}>
              <div style={{ fontSize: 11, color: '#888', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 8 }}>
                Conservative ({ruleN - 5}%)
              </div>
              <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, color: '#5ba3d9' }}>
                {fmt(conservativeOffer)}
              </div>
              <div style={{ fontSize: 11, color: '#666', marginTop: 4 }}>Safer margins</div>
            </div>
            <div style={{
              background: 'rgba(244,126,95,0.06)', border: '2px solid #ff7e5f', borderRadius: 10, padding: 20,
              textAlign: 'center', position: 'relative',
            }}>
              <div style={{
                position: 'absolute', top: -10, left: '50%', transform: 'translateX(-50%)',
                background: '#ff7e5f', color: '#000', fontSize: 10, fontWeight: 700,
                padding: '2px 10px', borderRadius: 4, letterSpacing: '0.06em',
              }}>
                RECOMMENDED
              </div>
              <div style={{ fontSize: 11, color: '#ff7e5f', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 8 }}>
                Standard ({ruleN}%)
              </div>
              <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 34, color: '#ff7e5f' }}>
                {fmt(mao)}
              </div>
              <div style={{ fontSize: 11, color: '#888', marginTop: 4 }}>Your offer price (MAO)</div>
            </div>
            <div style={{
              background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 20,
              textAlign: 'center', opacity: 0.8,
            }}>
              <div style={{ fontSize: 11, color: '#888', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 8 }}>
                Aggressive ({ruleN + 5}%)
              </div>
              <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 28, color: '#e8a44a' }}>
                {fmt(aggressiveOffer)}
              </div>
              <div style={{ fontSize: 11, color: '#666', marginTop: 4 }}>Tight margins</div>
            </div>
          </div>

          {/* Verdict */}
          {verdict && (
            <div style={{
              background: `${verdictColor}10`, border: `1px solid ${verdictColor}40`,
              borderRadius: 10, padding: '16px 20px', marginBottom: 24,
              display: 'flex', alignItems: 'center', gap: 12,
            }}>
              {investorROI >= 0.10 ? <CheckCircle2 size={22} color={verdictColor} /> : <AlertTriangle size={22} color={verdictColor} />}
              <div>
                <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 18, color: verdictColor, letterSpacing: '0.04em' }}>
                  {verdict}
                </div>
                <div style={{ fontSize: 12, color: '#888', marginTop: 2 }}>
                  Investor ROI: {pct(investorROI)} | Investor Profit: {fmt(investorProfit)} | Your Fee: {fmt(feeN)}
                </div>
              </div>
            </div>
          )}

          {/* Your Wholesale Profit */}
          <div style={{
            background: 'linear-gradient(135deg, rgba(244,126,95,0.08), rgba(255,179,71,0.04))',
            border: '1px solid rgba(244,126,95,0.2)',
            borderRadius: 10, padding: 24, marginBottom: 24,
          }}>
            <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 22, color: '#ff7e5f', letterSpacing: '0.04em', margin: '0 0 16px' }}>
              <PiggyBank size={20} style={{ display: 'inline', verticalAlign: '-3px', marginRight: 8 }} />
              Your Wholesale Profit Breakdown
            </h3>
            <div className="profit-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12 }}>
              <div style={{ background: '#263040', borderRadius: 8, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>Your Offer (MAO)</div>
                <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, color: '#f5f0eb' }}>{fmt(mao)}</div>
              </div>
              <div style={{ background: '#263040', borderRadius: 8, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>Assignment Fee</div>
                <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, color: '#5cb885' }}>{fmt(feeN)}</div>
              </div>
              <div style={{ background: '#263040', borderRadius: 8, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>Buyer Pays</div>
                <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, color: '#ffb347' }}>{fmt(mao + feeN)}</div>
              </div>
              <div style={{ background: '#263040', borderRadius: 8, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 11, color: '#888', marginBottom: 4 }}>Spread to ARV</div>
                <div style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 24, color: '#5ba3d9' }}>{fmt(arvN - mao - feeN)}</div>
              </div>
            </div>
          </div>

          {/* Investor Cost Breakdown */}
          <div style={{ background: '#263040', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
            <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#ffb347', letterSpacing: '0.04em', margin: '0 0 16px' }}>
              Investor Cost Breakdown
            </h3>
            <p style={{ fontSize: 12, color: '#888', marginBottom: 16, lineHeight: 1.6 }}>
              This is what your end buyer&apos;s numbers look like — understanding this helps you price deals better.
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {costs.map((c, i) => (
                <div key={i} style={{
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                  padding: '10px 14px', background: '#2e3a4d', borderRadius: 6,
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div style={{
                      width: 6, height: 6, borderRadius: '50%',
                      background: c.category === 'closing' ? '#5ba3d9' : c.category === 'rehab' ? '#e8a44a' : c.category === 'fee' ? '#ff7e5f' : '#a855f7',
                    }} />
                    <span style={{ fontSize: 13, color: '#ccc' }}>{c.label}</span>
                  </div>
                  <span style={{ fontSize: 14, color: '#f5f0eb', fontWeight: 600, fontFamily: "'DM Sans', sans-serif" }}>
                    {fmt(c.amount)}
                  </span>
                </div>
              ))}
              <div style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '12px 14px', background: '#3d4e65', borderRadius: 6, marginTop: 4,
              }}>
                <span style={{ fontSize: 14, color: '#ff7e5f', fontWeight: 700 }}>Total Investor Costs</span>
                <span style={{ fontSize: 16, color: '#ff7e5f', fontWeight: 700, fontFamily: "'Bebas Neue', sans-serif", letterSpacing: '0.04em' }}>
                  {fmt(totalCosts)}
                </span>
              </div>
            </div>
          </div>

          {/* Quick Script */}
          <div style={{ background: '#2e3a4d', border: '1px solid #3d4e65', borderRadius: 10, padding: 24, marginBottom: 24 }}>
            <h3 style={{ fontFamily: "'Bebas Neue', sans-serif", fontSize: 20, color: '#5cb885', letterSpacing: '0.04em', margin: '0 0 12px' }}>
              <Target size={18} style={{ display: 'inline', verticalAlign: '-3px', marginRight: 8 }} />
              Offer Script
            </h3>
            <div style={{
              background: '#263040', borderRadius: 8, padding: 16,
              fontFamily: "'DM Sans', sans-serif", fontSize: 14, color: '#ccc', lineHeight: 1.8,
              borderLeft: '3px solid #5cb885',
            }}>
              &ldquo;Based on my analysis, the property{address ? ` at ${address}` : ''} needs approximately <strong style={{ color: '#ff7e5f' }}>{fmt(repN)}</strong> in repairs.
              Comparable sales in the area suggest an after-repair value of around <strong style={{ color: '#ff7e5f' }}>{fmt(arvN)}</strong>.
              Given the current market conditions, I&apos;d like to offer <strong style={{ color: '#ff7e5f' }}>{fmt(mao)}</strong> — this is a fair cash offer that accounts for renovation costs and gives us both a good deal.
              I can close in as little as 14-21 days with no agent commissions or closing costs on your end.&rdquo;
            </div>
          </div>

          {/* Download button */}
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
            <button
              onClick={() => downloadOfferSheet(offerData)}
              className="btn-orange"
              style={{ padding: '12px 24px', fontSize: 14 }}
            >
              <Download size={14} /> Download Offer Sheet
            </button>
          </div>
        </div>
      )}

      {!calculated && (
        <div style={{
          textAlign: 'center', padding: '40px 20px', color: '#555',
          background: '#263040', border: '1px solid #3d4e65', borderRadius: 10,
        }}>
          <Calculator size={32} color="#333" style={{ marginBottom: 12 }} />
          <p style={{ fontSize: 14, margin: 0 }}>
            Enter the ARV and repair estimates above, then hit Calculate to see your offer range and full deal analysis.
          </p>
        </div>
      )}
    </div>
  )
}
