/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PracticeDealsRouteImport } from './routes/practice-deals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as FtcAdminRouteImport } from './routes/ftc-admin'
import { Route as FirstDealRouteImport } from './routes/first-deal'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmdVaultRouteImport } from './routes/emd-vault'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContractsLegalRouteImport } from './routes/contracts-legal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDealsRoute = PracticeDealsRouteImport.update({
  id: '/practice-deals',
  path: '/practice-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FtcAdminRoute = FtcAdminRouteImport.update({
  id: '/ftc-admin',
  path: '/ftc-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstDealRoute = FirstDealRouteImport.update({
  id: '/first-deal',
  path: '/first-deal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmdVaultRoute = EmdVaultRouteImport.update({
  id: '/emd-vault',
  path: '/emd-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsLegalRoute = ContractsLegalRouteImport.update({
  id: '/contracts-legal',
  path: '/contracts-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contracts-legal': typeof ContractsLegalRoute
  '/crm': typeof CrmRoute
  '/deals': typeof DealsRoute
  '/emd-vault': typeof EmdVaultRoute
  '/faq': typeof FaqRoute
  '/first-deal': typeof FirstDealRoute
  '/ftc-admin': typeof FtcAdminRoute
  '/getting-started': typeof GettingStartedRoute
  '/login': typeof LoginRoute
  '/practice-deals': typeof PracticeDealsRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contracts-legal': typeof ContractsLegalRoute
  '/crm': typeof CrmRoute
  '/deals': typeof DealsRoute
  '/emd-vault': typeof EmdVaultRoute
  '/faq': typeof FaqRoute
  '/first-deal': typeof FirstDealRoute
  '/ftc-admin': typeof FtcAdminRoute
  '/getting-started': typeof GettingStartedRoute
  '/login': typeof LoginRoute
  '/practice-deals': typeof PracticeDealsRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyers': typeof BuyersRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contracts-legal': typeof ContractsLegalRoute
  '/crm': typeof CrmRoute
  '/deals': typeof DealsRoute
  '/emd-vault': typeof EmdVaultRoute
  '/faq': typeof FaqRoute
  '/first-deal': typeof FirstDealRoute
  '/ftc-admin': typeof FtcAdminRoute
  '/getting-started': typeof GettingStartedRoute
  '/login': typeof LoginRoute
  '/practice-deals': typeof PracticeDealsRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyers'
    | '/checkout-success'
    | '/community'
    | '/contact'
    | '/contracts-legal'
    | '/crm'
    | '/deals'
    | '/emd-vault'
    | '/faq'
    | '/first-deal'
    | '/ftc-admin'
    | '/getting-started'
    | '/login'
    | '/practice-deals'
    | '/privacy'
    | '/properties'
    | '/settings'
    | '/terms'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyers'
    | '/checkout-success'
    | '/community'
    | '/contact'
    | '/contracts-legal'
    | '/crm'
    | '/deals'
    | '/emd-vault'
    | '/faq'
    | '/first-deal'
    | '/ftc-admin'
    | '/getting-started'
    | '/login'
    | '/practice-deals'
    | '/privacy'
    | '/properties'
    | '/settings'
    | '/terms'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/buyers'
    | '/checkout-success'
    | '/community'
    | '/contact'
    | '/contracts-legal'
    | '/crm'
    | '/deals'
    | '/emd-vault'
    | '/faq'
    | '/first-deal'
    | '/ftc-admin'
    | '/getting-started'
    | '/login'
    | '/practice-deals'
    | '/privacy'
    | '/properties'
    | '/settings'
    | '/terms'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyersRoute: typeof BuyersRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ContractsLegalRoute: typeof ContractsLegalRoute
  CrmRoute: typeof CrmRoute
  DealsRoute: typeof DealsRoute
  EmdVaultRoute: typeof EmdVaultRoute
  FaqRoute: typeof FaqRoute
  FirstDealRoute: typeof FirstDealRoute
  FtcAdminRoute: typeof FtcAdminRoute
  GettingStartedRoute: typeof GettingStartedRoute
  LoginRoute: typeof LoginRoute
  PracticeDealsRoute: typeof PracticeDealsRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-deals': {
      id: '/practice-deals'
      path: '/practice-deals'
      fullPath: '/practice-deals'
      preLoaderRoute: typeof PracticeDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ftc-admin': {
      id: '/ftc-admin'
      path: '/ftc-admin'
      fullPath: '/ftc-admin'
      preLoaderRoute: typeof FtcAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-deal': {
      id: '/first-deal'
      path: '/first-deal'
      fullPath: '/first-deal'
      preLoaderRoute: typeof FirstDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emd-vault': {
      id: '/emd-vault'
      path: '/emd-vault'
      fullPath: '/emd-vault'
      preLoaderRoute: typeof EmdVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts-legal': {
      id: '/contracts-legal'
      path: '/contracts-legal'
      fullPath: '/contracts-legal'
      preLoaderRoute: typeof ContractsLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyersRoute: BuyersRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ContractsLegalRoute: ContractsLegalRoute,
  CrmRoute: CrmRoute,
  DealsRoute: DealsRoute,
  EmdVaultRoute: EmdVaultRoute,
  FaqRoute: FaqRoute,
  FirstDealRoute: FirstDealRoute,
  FtcAdminRoute: FtcAdminRoute,
  GettingStartedRoute: GettingStartedRoute,
  LoginRoute: LoginRoute,
  PracticeDealsRoute: PracticeDealsRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
